/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dirs_work_JniHelper */

#ifndef _Included_com_dirs_work_JniHelper
#define _Included_com_dirs_work_JniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dirs_work_JniHelper
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dirs_work_JniHelper_init
  (JNIEnv *, jobject);

/*
 * Class:     com_dirs_work_JniHelper
 * Method:    getImage
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_dirs_work_JniHelper_getImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dirs_work_JniHelper
 * Method:    downloadImage
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dirs_work_JniHelper_downloadImage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
